config:
  prefix: '&f[&eTryVote&f]'
  command aliases:
    - 'tv'
    - 'vote'
    - 'tVote'
    - 'voteTry'
  reward commands:
    - ''
  messages:
    no permission: '&cNo permission'
    unknown command: '&cUnknown command. &fTry /%command% help'
    reloaded: '&aFiles reloaded!'
